-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.11 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6250
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for sliitiams
CREATE DATABASE IF NOT EXISTS `sliitiams` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;
USE `sliitiams`;

-- Dumping structure for table sliitiams.availability
CREATE TABLE IF NOT EXISTS `availability` (
  `startTime` varchar(50) DEFAULT NULL,
  `endTime` varchar(50) DEFAULT NULL,
  `day` varchar(50) DEFAULT NULL,
  `instroctorName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `batchid` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `location` varchar(100) NOT NULL,
  KEY `FK_availability_lectures_instroctors` (`instroctorName`),
  KEY `FK_availability_batches` (`batchid`),
  KEY `FK_availability_halls` (`location`),
  CONSTRAINT `FK_availability_batches` FOREIGN KEY (`batchid`) REFERENCES `batches` (`batchid`),
  CONSTRAINT `FK_availability_halls` FOREIGN KEY (`location`) REFERENCES `halls` (`hallname`),
  CONSTRAINT `FK_availability_lectures_instroctors` FOREIGN KEY (`instroctorName`) REFERENCES `lectures_instroctors` (`iname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.availability: ~0 rows (approximately)
DELETE FROM `availability`;
/*!40000 ALTER TABLE `availability` DISABLE KEYS */;
/*!40000 ALTER TABLE `availability` ENABLE KEYS */;

-- Dumping structure for table sliitiams.batches
CREATE TABLE IF NOT EXISTS `batches` (
  `BatchID` varchar(100) NOT NULL,
  PRIMARY KEY (`BatchID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.batches: ~113 rows (approximately)
DELETE FROM `batches`;
/*!40000 ALTER TABLE `batches` DISABLE KEYS */;
INSERT INTO `batches` (`BatchID`) VALUES
	('Y1.S1.WD.IT.01'),
	('Y1.S1.WD.IT.02'),
	('Y1.S1.WD.IT.03'),
	('Y1.S1.WD.IT.04'),
	('Y1.S1.WD.IT.05'),
	('Y1.S1.WD.IT.06'),
	('Y1.S1.WD.IT.07'),
	('Y1.S1.WD.IT.08'),
	('Y1.S1.WD.IT.09'),
	('Y1.S2.WD.CSNE.07'),
	('Y1.S2.WD.CSNE.08'),
	('Y1.S2.WD.IT.01'),
	('Y1.S2.WD.IT.02'),
	('Y1.S2.WD.IT.03'),
	('Y1.S2.WD.IT.04'),
	('Y1.S2.WD.IT.05'),
	('Y1.S2.WD.IT.06'),
	('Y1.S2.WE.CSNE.02'),
	('Y1.S2.WE.IT.01'),
	('Y2.S1.WD.CS.07'),
	('Y2.S1.WD.ISE.06'),
	('Y2.S1.WD.IT.01'),
	('Y2.S1.WD.IT.02'),
	('Y2.S1.WD.IT.03'),
	('Y2.S1.WD.IT.04'),
	('Y2.S1.WD.IT.05'),
	('Y2.S2.WD.CS.13'),
	('Y2.S2.WD.CS.14'),
	('Y2.S2.WD.CSNE.11'),
	('Y2.S2.WD.Foreign(CSNE).16'),
	('Y2.S2.WD.Foreign(IT/SE).15'),
	('Y2.S2.WD.ISE.12'),
	('Y2.S2.WD.IT.01'),
	('Y2.S2.WD.IT.02'),
	('Y2.S2.WD.IT.03'),
	('Y2.S2.WD.IT.04'),
	('Y2.S2.WD.IT.05'),
	('Y2.S2.WD.IT.06'),
	('Y2.S2.WD.IT.07'),
	('Y2.S2.WD.IT.08'),
	('Y2.S2.WD.IT.09'),
	('Y2.S2.WD.IT.10'),
	('Y2.S2.WE.CS.03'),
	('Y2.S2.WE.CSNE.02'),
	('Y2.S2.WE.ISE.04'),
	('Y2.S2.WE.IT.01'),
	('Y3.S1.WD.CS.05'),
	('Y3.S1.WD.CSNE.03'),
	('Y3.S1.WD.DS.06'),
	('Y3.S1.WD.ISE.04'),
	('Y3.S1.WD.IT.01'),
	('Y3.S1.WD.IT.02'),
	('Y3.S1.WD.SE.07'),
	('Y3.S1.WE.CS.03'),
	('Y3.S1.WE.CSNE.02'),
	('Y3.S1.WE.DS.06'),
	('Y3.S1.WE.IM.07'),
	('Y3.S1.WE.ISE.04'),
	('Y3.S1.WE.IT.01'),
	('Y3.S1.WE.SE.05'),
	('Y3.S2.WD.CS.08'),
	('Y3.S2.WD.CSNE.06'),
	('Y3.S2.WD.CurtinCSNE.11'),
	('Y3.S2.WD.CurtinIT.09'),
	('Y3.S2.WD.CurtinSE.10'),
	('Y3.S2.WD.DS.04'),
	('Y3.S2.WD.ISE.07'),
	('Y3.S2.WD.IT.01'),
	('Y3.S2.WD.IT.02'),
	('Y3.S2.WD.IT.03'),
	('Y3.S2.WD.SE.05'),
	('Y3.S2.WE.CS.13'),
	('Y3.S2.WE.CSNE.10'),
	('Y3.S2.WE.CSNE.11'),
	('Y3.S2.WE.DS.05'),
	('Y3.S2.WE.IM.09'),
	('Y3.S2.WE.ISE.12'),
	('Y3.S2.WE.IT.01'),
	('Y3.S2.WE.IT.02'),
	('Y3.S2.WE.IT.03'),
	('Y3.S2.WE.IT.04'),
	('Y3.S2.WE.SE.06'),
	('Y3.S2.WE.SE.07'),
	('Y3.S2.WE.SE.08'),
	('Y4.S1.WD.CS.06'),
	('Y4.S1.WD.CSNE.04'),
	('Y4.S1.WD.DS.02'),
	('Y4.S1.WD.ISE.05'),
	('Y4.S1.WD.IT.01'),
	('Y4.S1.WD.SE.03'),
	('Y4.S1.WE.CS.07'),
	('Y4.S1.WE.CSNE.05'),
	('Y4.S1.WE.DS.02'),
	('Y4.S1.WE.IM.04'),
	('Y4.S1.WE.ISE.06'),
	('Y4.S1.WE.IT.01'),
	('Y4.S1.WE.SE.03'),
	('Y4.S2.WD.CS.06'),
	('Y4.S2.WD.CSNE.04'),
	('Y4.S2.WD.DS.02'),
	('Y4.S2.WD.ISE.05'),
	('Y4.S2.WD.IT.01'),
	('Y4.S2.WD.SE.03'),
	('Y4.S2.WE.CS.10'),
	('Y4.S2.WE.CSNE.08'),
	('Y4.S2.WE.DS.04'),
	('Y4.S2.WE.IM.07'),
	('Y4.S2.WE.ISE.09'),
	('Y4.S2.WE.IT.01'),
	('Y4.S2.WE.IT.02'),
	('Y4.S2.WE.IT.03'),
	('Y4.S2.WE.SE.05'),
	('Y4.S2.WE.SE.06');
/*!40000 ALTER TABLE `batches` ENABLE KEYS */;

-- Dumping structure for table sliitiams.createaccount
CREATE TABLE IF NOT EXISTS `createaccount` (
  `empNo` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `userName` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `userType` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `repassword` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`empNo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.createaccount: ~12 rows (approximately)
DELETE FROM `createaccount`;
/*!40000 ALTER TABLE `createaccount` DISABLE KEYS */;
INSERT INTO `createaccount` (`empNo`, `userName`, `userType`, `password`, `repassword`) VALUES
	('1', 'sd', 'Admin', 's', NULL),
	('2', 'ee', 'Admin', '123456', '123456'),
	('22', 'ww', 'Academic Coordinator', '123456', '123456'),
	('222', 'ww', 'Academic Coordinator', '123456', '123456'),
	('22222', 'ww', 'Academic Coordinator', '123456', '123456'),
	('225', 'ww', 'Select User Type', '123456', '123456'),
	('4', 'ww', 'Select User Type', '123456', '123456'),
	('5', 'ww', 'Admin', '123456', '123456'),
	('Emp 011', 'Madushani', 'Admin', '123456', '123456'),
	('Emp001', 'Dulanji Cooray', 'Admin', '123456', '123456'),
	('Epm 03', 'Dulanji', 'Admin', '123456', '123456'),
	('ww', 'ww', 'Academic Coordinator', '123456', '123456');
/*!40000 ALTER TABLE `createaccount` ENABLE KEYS */;

-- Dumping structure for table sliitiams.halls
CREATE TABLE IF NOT EXISTS `halls` (
  `hallid` varchar(100) DEFAULT NULL,
  `hallname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `building` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `floor` varchar(100) DEFAULT NULL,
  `maxCapacity` varchar(100) DEFAULT NULL,
  `type` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`hallname`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.halls: ~61 rows (approximately)
DELETE FROM `halls`;
/*!40000 ALTER TABLE `halls` DISABLE KEYS */;
INSERT INTO `halls` (`hallid`, `hallname`, `building`, `floor`, `maxCapacity`, `type`) VALUES
	('1', '13H_A', NULL, NULL, NULL, NULL),
	('2', '13H_B', NULL, NULL, NULL, NULL),
	('3', '13H_C', NULL, NULL, NULL, NULL),
	('4', '13L_A + 13L_B', NULL, NULL, NULL, NULL),
	('5', '13L_B', NULL, NULL, NULL, NULL),
	('6', '13L_C', NULL, NULL, NULL, NULL),
	('7', '13L_D', NULL, NULL, NULL, NULL),
	('8', '13L_E1+ 13LE2', NULL, NULL, NULL, NULL),
	('9', '410A', NULL, NULL, NULL, NULL),
	('10', '410A+410B', NULL, NULL, NULL, NULL),
	('11', '410B', NULL, NULL, NULL, NULL),
	('12', '601', NULL, NULL, NULL, NULL),
	('13', '602', NULL, NULL, NULL, NULL),
	('14', '602+603', NULL, NULL, NULL, NULL),
	('15', '603', NULL, NULL, NULL, NULL),
	('16', '603-PC Lab', NULL, NULL, NULL, NULL),
	('17', '605', NULL, NULL, NULL, NULL),
	('18', 'A307', NULL, NULL, NULL, NULL),
	('19', 'A308', NULL, NULL, NULL, NULL),
	('20', 'A405-Pclab', NULL, NULL, NULL, NULL),
	('21', 'A406-Pclab', NULL, NULL, NULL, NULL),
	('22', 'A409-DClab', NULL, NULL, NULL, NULL),
	('23', 'A411-Pclab', NULL, NULL, NULL, NULL),
	('24', 'A505', NULL, NULL, NULL, NULL),
	('25', 'A506', NULL, NULL, NULL, NULL),
	('26', 'A507', NULL, NULL, NULL, NULL),
	('27', 'A509', NULL, NULL, NULL, NULL),
	('28', 'A705-Pclab', NULL, NULL, NULL, NULL),
	('29', 'A720-Pclab', NULL, NULL, NULL, NULL),
	('30', 'Auditorium', NULL, NULL, NULL, NULL),
	('31', 'B401-Pclab', NULL, NULL, NULL, NULL),
	('32', 'B402-Pclab', NULL, NULL, NULL, NULL),
	('33', 'B403-Pclab', NULL, NULL, NULL, NULL),
	('34', 'B404-CyberSecLab', NULL, NULL, NULL, NULL),
	('35', 'B406', NULL, NULL, NULL, NULL),
	('36', 'B501', NULL, NULL, NULL, NULL),
	('37', 'B502', NULL, NULL, NULL, NULL),
	('38', 'B509', NULL, NULL, NULL, NULL),
	('39', 'curtin lab', NULL, NULL, NULL, NULL),
	('40', 'E403', NULL, NULL, NULL, NULL),
	('41', 'E404', NULL, NULL, NULL, NULL),
	('42', 'F501', NULL, NULL, NULL, NULL),
	('43', 'F502', NULL, NULL, NULL, NULL),
	('44', 'Mini Audi', NULL, NULL, NULL, NULL),
	('45', 'MMLab', NULL, NULL, NULL, NULL),
	('46', 'N2A', NULL, NULL, NULL, NULL),
	('47', 'N3A-Pclab', NULL, NULL, NULL, NULL),
	('48', 'N3B', NULL, NULL, NULL, NULL),
	('49', 'N3C', NULL, NULL, NULL, NULL),
	('50', 'N3D', NULL, NULL, NULL, NULL),
	('51', 'N3E', NULL, NULL, NULL, NULL),
	('52', 'New-Cyber', NULL, NULL, NULL, NULL),
	('53', 'New-DClab', NULL, NULL, NULL, NULL),
	('54', 'New-Emblab', NULL, NULL, NULL, NULL),
	('55', 'New-Hall A', NULL, NULL, NULL, NULL),
	('56', 'New-Hall B', NULL, NULL, NULL, NULL),
	('57', 'New-Lab A', NULL, NULL, NULL, NULL),
	('58', 'New3B-lab', NULL, NULL, NULL, NULL),
	('59', 'New3C', NULL, NULL, NULL, NULL),
	('60', 'New4B-lab', NULL, NULL, NULL, NULL),
	('61', 'temp-lab', NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE `halls` ENABLE KEYS */;

-- Dumping structure for table sliitiams.lectures_instroctors
CREATE TABLE IF NOT EXISTS `lectures_instroctors` (
  `empno` varchar(200) DEFAULT NULL,
  `iname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `email` varchar(200) DEFAULT NULL,
  `phone` varchar(200) DEFAULT NULL,
  `department` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`iname`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.lectures_instroctors: ~68 rows (approximately)
DELETE FROM `lectures_instroctors`;
/*!40000 ALTER TABLE `lectures_instroctors` DISABLE KEYS */;
INSERT INTO `lectures_instroctors` (`empno`, `iname`, `email`, `phone`, `department`) VALUES
	(NULL, 'Aathika\r\n', NULL, NULL, NULL),
	(NULL, 'Achini Chathurangika\r\n', NULL, NULL, NULL),
	(NULL, 'Anushika\r\n', NULL, NULL, NULL),
	('1638\r\n', 'Buddhi Tharuka\r\n', NULL, NULL, NULL),
	('1605\r\n', 'Chathuni Umesha\r\n', 'dilanka.y@sliit.lk\r\n', '071-1733599\r\n', 'SE\r\n'),
	(NULL, 'Chathurangi Dhanushika Weerasinghe\r\n', 'chathurangi.w@sliit.lk\r\n', '713216020\r\n', 'IT\r\n'),
	(NULL, 'Chathuri\r\n', NULL, NULL, NULL),
	(NULL, 'Dakeela\r\n', NULL, NULL, NULL),
	('1630\r\n', 'Danushi Jayalath\r\n', NULL, NULL, NULL),
	('1647\r\n', 'Dhapitha Nesarajan(new)\r\n', NULL, NULL, NULL),
	('1635\r\n', 'Dilanka Nayanajith\r\n', NULL, NULL, NULL),
	(NULL, 'Divya\r\n', NULL, NULL, NULL),
	(NULL, 'Geeshani\r\n', NULL, NULL, NULL),
	('1523\r\n', 'Hansi Mayadunna\r\n', 'hansi.m@sliit.lk\r\n', '710530575\r\n', 'IT \r\n'),
	(NULL, 'Inisha Subasinghe\r\n', NULL, NULL, NULL),
	('1632\r\n', 'Ishana Dahanayake\r\n', NULL, NULL, NULL),
	(NULL, 'Isuri Dasnayaka (new)\r\n', NULL, NULL, NULL),
	('1582\r\n', 'J.M.D. Maheshika \r\n', 'dulani.m@sliit.lk\r\n', '077-2832200\r\n', 'IT \r\n'),
	('1519\r\n', 'Jayani Vimukthika Vithanage \r\n', 'jayani.v@sliit.lk\r\n', '719727434\r\n', 'IT\r\n'),
	('1575\r\n', 'Kalubowilage Madhura Priyankara Perera\r\n', 'madhura.p@sliit.lk\r\n', '071-2279720\r\n', 'SE\r\n'),
	(NULL, 'Kanchana\r\n', NULL, NULL, NULL),
	(NULL, 'Kashyapa\r\n', NULL, NULL, NULL),
	(NULL, 'M. T. Methmi Kaveesha', 'kaveesha.t@sliit.lk\r\n', '071-3330299\r\n', 'ISE\r\n'),
	('1404\r\n', 'M.Rashmi Shamindra Muthusinghe\r\n', 'rashmi.s@sliit.lk\r\n', '775469330\r\n', 'IT\r\n'),
	(NULL, 'Madhuni Prabashini\r\n', NULL, NULL, NULL),
	('1607\r\n', 'Madushi Prasangi Edirisinghe \r\n', 'madushi.e@sliit.lk\r\n', '071-5924932\r\n', 'IT \r\n'),
	(NULL, 'Menaka\r\n', NULL, NULL, NULL),
	(NULL, 'Mihiri\r\n', NULL, NULL, NULL),
	('1636\r\n', 'Mr. Kasun Jayananda\r\n', 'kasun.v@sliit.lk\r\n', '717312286\r\n', 'IT \r\n'),
	('1619', 'Ms. Ann Fernando', 'ann.f@sliit.lk\r\n', '766770709\r\n', 'ISE\r\n'),
	('1631\r\n', 'Ms.Baanujah Jeevanathan\r\n', 'baanujah.j@sliit.lk\r\n', '773560269\r\n', 'IT\r\n'),
	(NULL, 'Ms.Indika(new)\r\n', NULL, NULL, 'IT\r\n'),
	(NULL, 'Ms.Karthiga\r\n', NULL, NULL, 'SE\r\n'),
	(NULL, 'Ms.Mihitha hansani De Silva\r\n', 'mihitha.d@sliit.lk\r\n', '702082042\r\n', 'IT \r\n'),
	('1637\r\n', 'Navoda Halloluwa\r\n', NULL, NULL, NULL),
	(NULL, 'NEW CS\r\n', NULL, NULL, NULL),
	(NULL, 'NEW CSN2\r\n', NULL, NULL, NULL),
	(NULL, 'NEW CSN3\r\n', NULL, NULL, NULL),
	(NULL, 'NEW CSN4\r\n', NULL, NULL, NULL),
	(NULL, 'NEW IT12\r\n', NULL, NULL, NULL),
	(NULL, 'NEW IT13\r\n', NULL, NULL, NULL),
	(NULL, 'Nipun (New)\r\n', NULL, NULL, NULL),
	(NULL, 'Nirmani\r\n', NULL, NULL, NULL),
	('1646\r\n', 'Pipuni Wijesiri\r\n', NULL, NULL, NULL),
	('1518', 'Poornami\r\n', NULL, NULL, NULL),
	('1473\r\n', 'Poornima Harischandra\r\n', 'poornima.h@sliit.lk\r\n', '763963730\r\n', 'IT\r\n'),
	(NULL, 'Prabavi Bagya\r\n', NULL, NULL, NULL),
	(NULL, 'Pranavi\r\n', NULL, NULL, NULL),
	('1455', 'Pubudu Malith Mihiran\r\n', 'pubudu.n@sliit.lk\r\n', '077 5773725\r\n', 'IT \r\n'),
	(NULL, 'R.M Subashini Damayanthi Menike\r\n', 'subashini.m@sliit.lk\r\n', '071-6544247\r\n', 'IT \r\n'),
	(NULL, 'Rameesha Kankanamge\r\n', 'rameesha.k@sliit.lk\r\n', '714608216\r\n', 'IT \r\n'),
	(NULL, 'Rangi Prarthana-ISE\r\n', NULL, NULL, NULL),
	('1520\r\n', 'Rashandi Fernando\r\n', 'rashandi.f@sliit.lk\r\n', '710812413\r\n', 'IT \r\n'),
	(NULL, 'Samadhi dhananjana\r\n', NULL, NULL, NULL),
	(NULL, 'Sammani\r\n', NULL, NULL, NULL),
	(NULL, 'Sapna \r\n', NULL, NULL, NULL),
	(NULL, 'Sashi\r\n', NULL, NULL, NULL),
	(NULL, 'Sasini Hathurusinghe\r\n', NULL, NULL, 'IT\r\n'),
	(NULL, 'Sathira\r\n', NULL, NULL, NULL),
	(NULL, 'Schithra vinodani\r\n', 'sachinthra.t@sliit.lk\r\n', '712091683\r\n', 'IT\r\n'),
	('1648\r\n', 'Shevindi\r\n', NULL, NULL, NULL),
	(NULL, 'Sujeepan\r\n', NULL, NULL, NULL),
	(NULL, 'Sukanya\r\n', NULL, NULL, NULL),
	(NULL, 'Tharindu Damsara\r\n', NULL, NULL, NULL),
	('1529\r\n', 'Tharsika T\r\n', 'tharsika.t@sliit.lk\r\n', '778827437\r\n', 'IT \r\n'),
	(NULL, 'Tharushika\r\n', NULL, NULL, NULL),
	(NULL, 'Thisara Shyamalee', NULL, NULL, NULL),
	(NULL, 'WSS Perera\r\n', NULL, NULL, NULL);
/*!40000 ALTER TABLE `lectures_instroctors` ENABLE KEYS */;

-- Dumping structure for table sliitiams.modulelist
CREATE TABLE IF NOT EXISTS `modulelist` (
  `modulecode` varchar(100) NOT NULL,
  `moduleName` varchar(100) DEFAULT NULL,
  `academicYearSem` varchar(100) DEFAULT NULL,
  `lectureIncharge` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`modulecode`),
  KEY `FK_modulelist_lectures_instroctors` (`lectureIncharge`),
  CONSTRAINT `FK_modulelist_lectures_instroctors` FOREIGN KEY (`lectureIncharge`) REFERENCES `lectures_instroctors` (`iname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table sliitiams.modulelist: ~129 rows (approximately)
DELETE FROM `modulelist`;
/*!40000 ALTER TABLE `modulelist` DISABLE KEYS */;
INSERT INTO `modulelist` (`modulecode`, `moduleName`, `academicYearSem`, `lectureIncharge`) VALUES
	('CCP1', NULL, NULL, NULL),
	('CMPE2000-DNCM', NULL, NULL, NULL),
	('CMPE3002-CTP1', NULL, NULL, NULL),
	('CMPE3002/CNCO3000-WDN', NULL, NULL, NULL),
	('CMPE3004-DN', NULL, NULL, NULL),
	('COMP1005-FP', NULL, NULL, NULL),
	('COMP1007-PDI', NULL, NULL, NULL),
	('COMP2001-HF', NULL, NULL, NULL),
	('COMP2006 - OS', NULL, NULL, NULL),
	('COMP3008-DC', NULL, NULL, NULL),
	('CSIE2010-DE', NULL, NULL, NULL),
	('CSIE2050-DCNM', NULL, NULL, NULL),
	('CSIE2080-DSA', NULL, NULL, NULL),
	('CSIT2020-OOSE', NULL, NULL, NULL),
	('CSIT2030-OOPD', NULL, NULL, NULL),
	('CSIT2040-DS', NULL, NULL, NULL),
	('CSIT2050-DCNM', NULL, NULL, NULL),
	('CSIT2060-USP', NULL, NULL, NULL),
	('ICTE3002-HCI', NULL, NULL, NULL),
	('IE2010-DE', NULL, NULL, NULL),
	('IE2012-SNP', NULL, NULL, NULL),
	('IE2020-RS', NULL, NULL, NULL),
	('IE2021-OOP', NULL, NULL, NULL),
	('IE2022-ICS', NULL, NULL, NULL),
	('IE2030-AE', NULL, NULL, NULL),
	('IE2030-OOP', NULL, NULL, NULL),
	('IE2031-SAD', NULL, NULL, NULL),
	('IE2032-SOS', NULL, NULL, NULL),
	('IE2040-AI', NULL, NULL, NULL),
	('IE2041-ISA', NULL, NULL, NULL),
	('IE2042-DMSS', NULL, NULL, NULL),
	('IE2050-OS', NULL, NULL, NULL),
	('IE2051-ISP', NULL, NULL, NULL),
	('IE2052-ANT', NULL, NULL, NULL),
	('IE2060-CSA', NULL, NULL, NULL),
	('IE2062-WS', NULL, NULL, NULL),
	('IE2070-ES', NULL, NULL, NULL),
	('IE2071-DMCI', NULL, NULL, NULL),
	('IE2072-FA', NULL, NULL, NULL),
	('IE2080-DSA', NULL, NULL, NULL),
	('IE2082-DM', NULL, NULL, NULL),
	('IE2090-PEPIM', NULL, NULL, NULL),
	('IE3010-NP', NULL, NULL, NULL),
	('IE3011-ISPM', NULL, NULL, NULL),
	('IE3020-DSNM', NULL, NULL, NULL),
	('IE3021-OBF I', NULL, NULL, NULL),
	('IE3022-AIA', NULL, NULL, NULL),
	('IE3030-WAN', NULL, NULL, NULL),
	('IE3031-MIS', NULL, NULL, NULL),
	('IE3032-NS', NULL, NULL, NULL),
	('IE3040-ISM', NULL, NULL, NULL),
	('IE3041-DMBI', NULL, NULL, NULL),
	('IE3042-SSS', NULL, NULL, NULL),
	('IE3050-WC', NULL, NULL, NULL),
	('IE3051-EBSAD', NULL, NULL, NULL),
	('IE3052-ISRM', NULL, NULL, NULL),
	('IE3060-BMIT', NULL, NULL, NULL),
	('IE3070-NTP', NULL, NULL, NULL),
	('IE3080-NSE', NULL, NULL, NULL),
	('IE3092-ISP', NULL, NULL, NULL),
	('IE3112-MS', NULL, NULL, NULL),
	('IE4010-ISM', NULL, NULL, NULL),
	('IE4011-BPM', NULL, NULL, NULL),
	('IE4012-OHTS', NULL, NULL, NULL),
	('IE4022-SEA', NULL, NULL, NULL),
	('IE4040-IAA', NULL, NULL, NULL),
	('IE4042-SSE', NULL, NULL, NULL),
	('IE4060 -RIS', NULL, NULL, NULL),
	('IE4062-CFIR', NULL, NULL, NULL),
	('IE4080-SDN', NULL, NULL, NULL),
	('IE4092-MLCS', NULL, NULL, NULL),
	('IE4151-HRIS', NULL, NULL, NULL),
	('INDE1001-EFPDC', NULL, NULL, NULL),
	('ISAD1000-ISE', NULL, NULL, NULL),
	('ISEC2001-FCDS', NULL, NULL, NULL),
	('IT1010-IP', NULL, NULL, NULL),
	('IT1020-ICS', NULL, NULL, NULL),
	('IT1030-MC', NULL, NULL, NULL),
	('IT1040-CS', NULL, NULL, NULL),
	('IT1050-OOC', NULL, NULL, NULL),
	('IT1060-SPM', NULL, NULL, NULL),
	('IT1080-EAP', NULL, NULL, NULL),
	('IT1090-ISDM', NULL, NULL, NULL),
	('IT1100-IWT', NULL, NULL, NULL),
	('IT2010-MAD', NULL, NULL, NULL),
	('IT2020-SE', NULL, NULL, NULL),
	('IT2030-OOP', NULL, NULL, NULL),
	('IT2040-DMS', NULL, NULL, NULL),
	('IT2050-CN', NULL, NULL, NULL),
	('IT2060-OSSA', NULL, NULL, NULL),
	('IT2070-DSA', NULL, NULL, NULL),
	('IT2080-ITP', NULL, NULL, NULL),
	('IT2090-ProfSkills', NULL, NULL, NULL),
	('IT2100-ESD', NULL, NULL, NULL),
	('IT2110-PS', NULL, NULL, NULL),
	('IT3010-NDM', NULL, NULL, NULL),
	('IT3011-TPSM', NULL, NULL, NULL),
	('IT3020-DS', NULL, NULL, NULL),
	('IT3021-DWBI', NULL, NULL, NULL),
	('IT3030-PAF', NULL, NULL, NULL),
	('IT3031-DSDA', NULL, NULL, NULL),
	('IT3040-ITPM', NULL, NULL, NULL),
	('IT3050-ESD', NULL, NULL, NULL),
	('IT3060-HCI', NULL, NULL, NULL),
	('IT3070-IAS', NULL, NULL, NULL),
	('IT3080-DA', NULL, NULL, NULL),
	('IT3090-BMIT', NULL, NULL, NULL),
	('IT4010-RP', NULL, NULL, NULL),
	('IT4020-MTIT', NULL, NULL, NULL),
	('IT4021-IOTBDA', NULL, NULL, NULL),
	('IT4031-VAUED', NULL, NULL, NULL),
	('IT4060 -ML', NULL, NULL, NULL),
	('IT4070-PPW', NULL, NULL, NULL),
	('IT4100-SQA', NULL, NULL, NULL),
	('IT4110 -CSNA', NULL, NULL, NULL),
	('IT4130-IUP', NULL, NULL, NULL),
	('MATH1019-LASE', NULL, NULL, NULL),
	('MC prac / IP exam', NULL, NULL, NULL),
	('NPSC1003-IISS', NULL, NULL, NULL),
	('SE3010-SEPQM', NULL, NULL, NULL),
	('SE3020-DS', NULL, NULL, NULL),
	('SE3030-SA', NULL, NULL, NULL),
	('SE3040-AF', NULL, NULL, NULL),
	('SE3050-UEE', NULL, NULL, NULL),
	('SE3060-DBS', NULL, NULL, NULL),
	('SE3070-CSSE', NULL, NULL, NULL),
	('SE3080-SPM', NULL, NULL, NULL),
	('SE4010-CTSE', NULL, NULL, NULL),
	('SE4020-MADD', NULL, NULL, NULL);
/*!40000 ALTER TABLE `modulelist` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
